before_script:
  - export CI_DISABLE_CURNN_TEST=true

variables:
  CI_IMAGE_TAG: 'cuda'

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v3/common.yml'

test:v1.0:
  extends: .test
  variables:
    CI_VERSION_TAG: 'v1.0'

test:v1.1:
  extends: .test
  variables:
    CI_VERSION_TAG: 'v1.1'

test:v1.2:
  extends: .test
  variables:
    CI_VERSION_TAG: 'v1.2'
